name: Build Client
on:
  push:
    branches: [master]
    paths:
      - .github/**
      - app/client/**
  pull_request:
    paths:
      - .github/**
      - app/client/**

jobs:
  client-build:
    name: "Build Client"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: "app/client"
          sparse-checkout-cone-mode: false

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        working-directory: ./app/client
        run: yarn install --immutable

      - name: Build
        working-directory: ./app/client
        run: yarn run build
